# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I1N44fIb5Pc3ui_6HCDRv9sPdZIhFH0E
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import plot_tree
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
import numpy as np
df=sns.load_dataset('tips')
df['high_tip']=(df['tip']>=3).astype(int)
df_encoded=pd.get_dummies(df,columns=['sex','smoker','day','time'],drop_first=True)
df_encoded=df_encoded.drop('tip',axis=1)
df_encoded['bill_per_person']=(df_encoded['total_bill']/df_encoded['size'])
features=['total_bill','size','bill_per_person','smoker_No','day_Sun','time_Dinner']
x=df_encoded[features]
y=df_encoded['high_tip']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
print("training set size ",x_train.shape )
print("test set size",x_test.shape)
print("class distribution ",y.value_counts())
df_unlimited=DecisionTreeClassifier(random_state=42)
df_unlimited.fit(x_train,y_train)
train_acc=df_unlimited.score(x_train,y_train)
test_acc=df_unlimited.score(x_test,y_test)
print("\n--- Unlimited Tree (overfitting example) ---")
print(f"Training Accuracy : {train_acc:.3f}")
print(f"Test Accuracy     : {test_acc:.3f}")
print(f"Tree Depth        : {df_unlimited.get_depth()}")
print(f"Number of leaves  : {df_unlimited.get_n_leaves()}")
dt_controlled=DecisionTreeClassifier(max_depth=3,random_state=42)
dt_controlled.fit(x_train,y_train)
train_acc_c=dt_controlled.score(x_train,y_train)
test_acc_c=dt_controlled.score(x_test,y_test)
print("\n--- Controlled Tree (max_depth=3) ---")
print(f"Training Accuracy : {train_acc_c:.3f}")
print(f"Test Accuracy     : {test_acc_c:.3f}")
print(f"Tree Depth        : {dt_controlled.get_depth()}")
print(f"Number of leaves  : {dt_controlled.get_n_leaves()}")
cv_unlimited=cross_val_score(df_unlimited,x,y,cv=5)
cv_controlled=cross_val_score(dt_controlled,x,y,cv=5)
print("\n--- Cross Validation Results ---")
print(f"Unlimited Tree CV : {cv_unlimited.mean():.3f} "
      f"+/- {cv_unlimited.std():.3f}")
print(f"Controlled Tree CV: {cv_controlled.mean():.3f} "
      f"+/- {cv_controlled.std():.3f}")

plt.figure(figsize=(20, 8))
plot_tree(dt_controlled,
          feature_names=features,
          class_names=['Low Tip', 'High Tip'],
          filled=True,
          rounded=True,
          fontsize=10)
plt.title('Decision Tree (max_depth=3)')
plt.tight_layout()
plt.show()

_